-- Deprecated compatibility entry point.
--
-- Yearly hardening is now versioned by individual migration files:
--   db/migrations/yearly/V001__add_yearly_performance_indexes.sql
--   db/migrations/yearly/V002__add_recepcion_primary_key.sql
--
-- This file intentionally contains no executable DDL so a manual invocation
-- cannot apply multiple untracked structural changes at once.
