IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'EVANS')
	BEGIN
		CREATE DATABASE [EVANS]
	END
    GO

USE [EVANS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESTADO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ESTADO](
	[ESTA_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[ESTA_DESCRIPCION] [nvarchar](20) NULL,
 CONSTRAINT [PK_ESTADO] PRIMARY KEY CLUSTERED 
(
	[ESTA_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UNIDAD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[UNIDAD](
	[UNID_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[UNID_DESCRIPCION] [nvarchar](30) NULL,
 CONSTRAINT [PK_UNIDAD] PRIMARY KEY CLUSTERED 
(
	[UNID_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[USUARIO](
	[USU_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[USU_NOMBREUSUARIO] [varchar](50) NOT NULL,
	[USU_CLAVE] [varchar](30) NULL,
	[USU_NOMBRECOMPLETO] [varchar](70) NULL,
	[USU_ADMIN] [int] NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[USU_NOMBREUSUARIO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DIRECCIONCLIENTE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DIRECCIONCLIENTE](
	[CLIE_CODIGO] [int] NULL,
	[CLIE_DIRECCION] [nvarchar](70) NULL,
	[CLIE_CIUDAD] [nvarchar](50) NULL,
	[CLIE_PROVINCIA] [nvarchar](50) NULL
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CLIENTE](
	[CLIE_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CLIE_NOMBRE] [nvarchar](70) NULL,
	[IDEN_CODIGO] [int] NULL,
	[CLIE_NROIDENTIFICACION] [nvarchar](11) NULL,
	[CLIE_TELEFONO] [nvarchar](50) NULL,
	[CLIE_FAX] [nvarchar](30) NULL,
	[CLIE_EMAIL] [nvarchar](50) NULL,
	[CLIE_REPRESENTANTE] [nvarchar](70) NULL,
 CONSTRAINT [PK_CLIENTE_1] PRIMARY KEY CLUSTERED 
(
	[CLIE_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPOIDENTIFICACION]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TIPOIDENTIFICACION](
	[IDEN_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[IDEN_DESCRIPCION] [nvarchar](15) NULL,
 CONSTRAINT [PK_TIPOIDENTIFICACION] PRIMARY KEY CLUSTERED 
(
	[IDEN_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PARAMETROS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PARAMETROS](
	[PARA_IGV] [float] NULL,
	[PARA_FACTSERIE] [nvarchar](4) NULL,
	[PARA_FACTNRO1] [nvarchar](6) NULL,
	[PARA_FACTNRO2] [nvarchar](6) NULL,
	[PARA_BOLSERIE] [nvarchar](4) NULL,
	[PARA_BOLNRO1] [nvarchar](6) NULL,
	[PARA_BOLNRO2] [nvarchar](6) NULL,
	[PARA_GREMSERIE] [nvarchar](4) NULL,
	[PARA_GREMNRO1] [nvarchar](6) NULL,
	[PARA_GREMNRO2] [nvarchar](6) NULL,
	[PARA_MANIFIESTO] [nvarchar](15) NULL,
	[PARA_REMITENTE] [nvarchar](70) NULL,
	[PARA_EMAILREMITENTE] [nvarchar](70) NULL,
	[PARA_PASSREMITENTE] [nvarchar](30) NULL,
	[PARA_SMTP] [nvarchar](50) NULL,
	[PARA_PUERTO] [int] NULL
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[AGENCIA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[AGENCIA](
	[AGEN_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[AGEN_DIRECCION] [varchar](100) NULL,
	[DEST_CODIGO] [int] NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_AGENCIA] PRIMARY KEY CLUSTERED 
(
	[AGEN_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VEHICULO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[VEHICULO](
	[VEHI_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[VEHI_MARCA] [nvarchar](50) NULL,
	[VEHI_PLACA] [nvarchar](10) NULL,
	[VEHI_CONFVEHICULAR] [nvarchar](5) NULL,
	[VEHI_CERTINSCRIPCION] [nvarchar](15) NULL,
	[EMPR_CODIGO] [int] NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_VEHICULO] PRIMARY KEY CLUSTERED 
(
	[VEHI_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CHOFER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CHOFER](
	[CHOF_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CHOF_NOMBRE] [nvarchar](70) NULL,
	[CHOF_LICENCIA] [nvarchar](15) NULL,
	[CHOF_TELEFONO] [nvarchar](15) NULL,
	[CHOF_DIRECCION] [nvarchar](70) NULL,
	[EMPR_CODIGO] [int] NOT NULL,
	[ESTA_CODIGO] [int] NOT NULL,
 CONSTRAINT [PK_CHOFER] PRIMARY KEY CLUSTERED 
(
	[CHOF_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CARRETA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CARRETA](
	[CARR_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CARR_PLACA] [nvarchar](10) NULL,
	[CARR_MARCA] [nvarchar](50) NULL,
	[CARR_CERTIFICADO] [nvarchar](15) NULL,
	[EMPR_CODIGO] [int] NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_CARRETA] PRIMARY KEY CLUSTERED 
(
	[CARR_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPOCOMPROBANTE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TIPOCOMPROBANTE](
	[TICO_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[TICO_DESCRIPCION] [varchar](20) NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_TIPOCOMPROBANTE] PRIMARY KEY CLUSTERED 
(
	[TICO_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DESTINO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DESTINO](
	[DEST_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DEST_NOMBRE] [nvarchar](40) NULL,
	[DEST_DISTANCIAVIRTUAL] [float] NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_DESTINO] PRIMARY KEY CLUSTERED 
(
	[DEST_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPRESA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[EMPRESA](
	[EMPR_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[EMPR_NOMBRE] [nvarchar](70) NULL,
	[EMPR_DIRECCION] [nvarchar](70) NULL,
	[EMPR_TELEFONO] [nvarchar](15) NULL,
	[EMPR_RUC] [nvarchar](11) NULL,
	[EMPR_PROPIEDAD] [bit] NULL,
	[ESTA_CODIGO] [int] NULL,
 CONSTRAINT [PK_EMPRESA] PRIMARY KEY CLUSTERED 
(
	[EMPR_CODIGO] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
USE [EVANS]
GO
USE [EVANS]
GO
USE [EVANS]
GO
USE [EVANS]
GO
USE [EVANS]
GO
USE [EVANS]
GO
USE [EVANS]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AGENCIA_DESTINO]') AND parent_object_id = OBJECT_ID(N'[dbo].[AGENCIA]'))
ALTER TABLE [dbo].[AGENCIA]  WITH CHECK ADD  CONSTRAINT [FK_AGENCIA_DESTINO] FOREIGN KEY([DEST_CODIGO])
REFERENCES [dbo].[DESTINO] ([DEST_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AGENCIA_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[AGENCIA]'))
ALTER TABLE [dbo].[AGENCIA]  WITH CHECK ADD  CONSTRAINT [FK_AGENCIA_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VEHICULO_REFERENCE_EMPRESA]') AND parent_object_id = OBJECT_ID(N'[dbo].[VEHICULO]'))
ALTER TABLE [dbo].[VEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_VEHICULO_REFERENCE_EMPRESA] FOREIGN KEY([EMPR_CODIGO])
REFERENCES [dbo].[EMPRESA] ([EMPR_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VEHICULO_REFERENCE_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[VEHICULO]'))
ALTER TABLE [dbo].[VEHICULO]  WITH CHECK ADD  CONSTRAINT [FK_VEHICULO_REFERENCE_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHOFER_EMPRESA]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHOFER]'))
ALTER TABLE [dbo].[CHOFER]  WITH CHECK ADD  CONSTRAINT [FK_CHOFER_EMPRESA] FOREIGN KEY([EMPR_CODIGO])
REFERENCES [dbo].[EMPRESA] ([EMPR_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CHOFER_REFERENCE_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CHOFER]'))
ALTER TABLE [dbo].[CHOFER]  WITH CHECK ADD  CONSTRAINT [FK_CHOFER_REFERENCE_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CARRETA_EMPRESA]') AND parent_object_id = OBJECT_ID(N'[dbo].[CARRETA]'))
ALTER TABLE [dbo].[CARRETA]  WITH CHECK ADD  CONSTRAINT [FK_CARRETA_EMPRESA] FOREIGN KEY([EMPR_CODIGO])
REFERENCES [dbo].[EMPRESA] ([EMPR_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CARRETA_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CARRETA]'))
ALTER TABLE [dbo].[CARRETA]  WITH CHECK ADD  CONSTRAINT [FK_CARRETA_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TIPOCOMPROBANTE_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[TIPOCOMPROBANTE]'))
ALTER TABLE [dbo].[TIPOCOMPROBANTE]  WITH CHECK ADD  CONSTRAINT [FK_TIPOCOMPROBANTE_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DESTINO_REFERENCE_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[DESTINO]'))
ALTER TABLE [dbo].[DESTINO]  WITH CHECK ADD  CONSTRAINT [FK_DESTINO_REFERENCE_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_EMPRESA_REFERENCE_ESTADO]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPRESA]'))
ALTER TABLE [dbo].[EMPRESA]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_REFERENCE_ESTADO] FOREIGN KEY([ESTA_CODIGO])
REFERENCES [dbo].[ESTADO] ([ESTA_CODIGO])